name: build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run build
      - name: run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: HEADLESS_ELECTRON_STARTUP_ARGS="--headless --use-gl=egl" npm test
        env:
          CI: true
