name: build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run build
      - run: xvfb-run -a npm test --ci
        if: ${{ runner.os == 'linux' }}
        env:
          HEADLESS_ELECTRON_STARTUP_ARGS: "--headless --use-gl=egl"
          NODE_ENV: test

      - run: npm test --ci
        if: ${{ runner.os != 'linux' }}
        env:
          HEADLESS_ELECTRON_STARTUP_ARGS: "--headless --use-gl=egl"
          NODE_ENV: test
